### ISSUE TITLE
Switch to fomantic-ui in admin page

### ISSUE THREAD

**Issue by lubber-de** [Novartis/YADA#115]
Semantic UI hasn't been maintained since 2018, but the active community fork https://fomantic-ui.com already got 500 bugfixes and new features like calendar, slider, toast, etc.

it is backward compatible, the current code should work as it is.

https://fomantic-ui.com
https://github.com/fomantic/fomantic-ui

**Comment by varontron** [comment]
current admin tool is obsolete.  if a new one is written it will use vuetify
